// Code generated by `ggen -ent AssociatedGroups -conf -coll`; DO NOT EDIT.

package api

// Conf receives custom request config definition, e.g. custom headers, custom OData mod
func (groups *AssociatedGroups) Conf(config *RequestConfig) *AssociatedGroups {
	groups.config = config
	return groups
}
