// Code generated by `ggen -ent Attachments -item Attachment -coll -helpers Data,Normalized`; DO NOT EDIT.

package api

/* Response helpers */

// Data response helper
func (attachmentsResp *AttachmentsResp) Data() []AttachmentResp {
	collection, _ := normalizeODataCollection(*attachmentsResp)
	attachments := []AttachmentResp{}
	for _, item := range collection {
		attachments = append(attachments, AttachmentResp(item))
	}
	return attachments
}

// Normalized returns normalized body
func (attachmentsResp *AttachmentsResp) Normalized() []byte {
	normalized, _ := NormalizeODataCollection(*attachmentsResp)
	return normalized
}
