// Code generated by `ggen -ent Attachment -helpers Data,Normalized`; DO NOT EDIT.

package api

import "encoding/json"

/* Response helpers */

// Data response helper
func (attachmentResp *AttachmentResp) Data() *AttachmentInfo {
	data := NormalizeODataItem(*attachmentResp)
	res := &AttachmentInfo{}
	json.Unmarshal(data, &res)
	return res
}

// Normalized returns normalized body
func (attachmentResp *AttachmentResp) Normalized() []byte {
	return NormalizeODataItem(*attachmentResp)
}
