// Code generated by `ggen -ent Changes -conf -coll -mods Top`; DO NOT EDIT.

package api

// Conf receives custom request config definition, e.g. custom headers, custom OData mod
func (changes *Changes) Conf(config *RequestConfig) *Changes {
	changes.config = config
	return changes
}

// Top adds $top OData modifier
func (changes *Changes) Top(oDataTop int) *Changes {
	changes.modifiers.AddTop(oDataTop)
	return changes
}
