// Code generated by `ggen -ent EventReceivers -conf -coll -mods Select,Filter,Top,OrderBy`; DO NOT EDIT.

package api

// Conf receives custom request config definition, e.g. custom headers, custom OData mod
func (receivers *EventReceivers) Conf(config *RequestConfig) *EventReceivers {
	receivers.config = config
	return receivers
}

// Select adds $select OData modifier
func (receivers *EventReceivers) Select(oDataSelect string) *EventReceivers {
	receivers.modifiers.AddSelect(oDataSelect)
	return receivers
}

// Filter adds $filter OData modifier
func (receivers *EventReceivers) Filter(oDataFilter string) *EventReceivers {
	receivers.modifiers.AddFilter(oDataFilter)
	return receivers
}

// Top adds $top OData modifier
func (receivers *EventReceivers) Top(oDataTop int) *EventReceivers {
	receivers.modifiers.AddTop(oDataTop)
	return receivers
}

// OrderBy adds $orderby OData modifier
func (receivers *EventReceivers) OrderBy(oDataOrderBy string, ascending bool) *EventReceivers {
	receivers.modifiers.AddOrderBy(oDataOrderBy, ascending)
	return receivers
}
