// Code generated by `ggen -ent FieldLink -helpers Data,Normalized`; DO NOT EDIT.

package api

import (
	"encoding/json"
)

/* Response helpers */

// Data response helper
func (fieldLinkResp *FieldLinkResp) Data() *FieldLinkInfo {
	data := NormalizeODataItem(*fieldLinkResp)
	res := &FieldLinkInfo{}
	json.Unmarshal(data, &res)
	return res
}

// Normalized returns normalized body
func (fieldLinkResp *FieldLinkResp) Normalized() []byte {
	return NormalizeODataItem(*fieldLinkResp)
}
