// Code generated by `ggen -ent Files -item File -conf -coll -mods Select,Expand,Filter,Top,Skip,OrderBy -helpers Data,Normalized,Pagination`; DO NOT EDIT.

package api

import (
	"fmt"
)

// Conf receives custom request config definition, e.g. custom headers, custom OData mod
func (files *Files) Conf(config *RequestConfig) *Files {
	files.config = config
	return files
}

// Select adds $select OData modifier
func (files *Files) Select(oDataSelect string) *Files {
	files.modifiers.AddSelect(oDataSelect)
	return files
}

// Expand adds $expand OData modifier
func (files *Files) Expand(oDataExpand string) *Files {
	files.modifiers.AddExpand(oDataExpand)
	return files
}

// Filter adds $filter OData modifier
func (files *Files) Filter(oDataFilter string) *Files {
	files.modifiers.AddFilter(oDataFilter)
	return files
}

// Top adds $top OData modifier
func (files *Files) Top(oDataTop int) *Files {
	files.modifiers.AddTop(oDataTop)
	return files
}

// Skip adds $skiptoken OData modifier
func (files *Files) Skip(skipToken string) *Files {
	files.modifiers.AddSkip(skipToken)
	return files
}

// OrderBy adds $orderby OData modifier
func (files *Files) OrderBy(oDataOrderBy string, ascending bool) *Files {
	files.modifiers.AddOrderBy(oDataOrderBy, ascending)
	return files
}

/* Response helpers */

// Data response helper
func (filesResp *FilesResp) Data() []FileResp {
	collection, _ := normalizeODataCollection(*filesResp)
	files := []FileResp{}
	for _, item := range collection {
		files = append(files, FileResp(item))
	}
	return files
}

// Normalized returns normalized body
func (filesResp *FilesResp) Normalized() []byte {
	normalized, _ := NormalizeODataCollection(*filesResp)
	return normalized
}

/* Pagination helpers */

// FilesPage - paged items
type FilesPage struct {
	Items       FilesResp
	HasNextPage func() bool
	GetNextPage func() (*FilesPage, error)
}

// GetPaged gets Paged Items collection
func (files *Files) GetPaged() (*FilesPage, error) {
	data, err := files.Get()
	if err != nil {
		return nil, err
	}
	res := &FilesPage{
		Items: data,
		HasNextPage: func() bool {
			return data.HasNextPage()
		},
		GetNextPage: func() (*FilesPage, error) {
			nextURL := data.NextPageURL()
			if nextURL == "" {
				return nil, fmt.Errorf("unable to get next page")
			}
			return NewFiles(files.client, nextURL, files.config).GetPaged()
		},
	}
	return res, nil
}

// NextPageURL gets next page OData collection
func (filesResp *FilesResp) NextPageURL() string {
	return getODataCollectionNextPageURL(*filesResp)
}

// HasNextPage returns is true if next page exists
func (filesResp *FilesResp) HasNextPage() bool {
	return filesResp.NextPageURL() != ""
}
