// Code generated by `ggen -ent Item -conf -mods Select,Expand -helpers Normalized,ToMap`; DO NOT EDIT.

package api

import (
	"encoding/json"
)

// Conf receives custom request config definition, e.g. custom headers, custom OData mod
func (item *Item) Conf(config *RequestConfig) *Item {
	item.config = config
	return item
}

// Select adds $select OData modifier
func (item *Item) Select(oDataSelect string) *Item {
	item.modifiers.AddSelect(oDataSelect)
	return item
}

// Expand adds $expand OData modifier
func (item *Item) Expand(oDataExpand string) *Item {
	item.modifiers.AddExpand(oDataExpand)
	return item
}

/* Response helpers */

// Normalized returns normalized body
func (itemResp *ItemResp) Normalized() []byte {
	return NormalizeODataItem(*itemResp)
}

// ToMap unmarshals response to generic map
func (itemResp *ItemResp) ToMap() map[string]interface{} {
	data := NormalizeODataItem(*itemResp)
	var res map[string]interface{}
	_ = json.Unmarshal(data, &res)
	return res
}
