// Code generated by `ggen -ent Lists -item List -conf -coll -mods Select,Expand,Filter,Top,Skip,OrderBy -helpers Data,Normalized,Pagination`; DO NOT EDIT.

package api

import (
	"fmt"
)

// Conf receives custom request config definition, e.g. custom headers, custom OData mod
func (lists *Lists) Conf(config *RequestConfig) *Lists {
	lists.config = config
	return lists
}

// Select adds $select OData modifier
func (lists *Lists) Select(oDataSelect string) *Lists {
	lists.modifiers.AddSelect(oDataSelect)
	return lists
}

// Expand adds $expand OData modifier
func (lists *Lists) Expand(oDataExpand string) *Lists {
	lists.modifiers.AddExpand(oDataExpand)
	return lists
}

// Filter adds $filter OData modifier
func (lists *Lists) Filter(oDataFilter string) *Lists {
	lists.modifiers.AddFilter(oDataFilter)
	return lists
}

// Top adds $top OData modifier
func (lists *Lists) Top(oDataTop int) *Lists {
	lists.modifiers.AddTop(oDataTop)
	return lists
}

// Skip adds $skiptoken OData modifier
func (lists *Lists) Skip(skipToken string) *Lists {
	lists.modifiers.AddSkip(skipToken)
	return lists
}

// OrderBy adds $orderby OData modifier
func (lists *Lists) OrderBy(oDataOrderBy string, ascending bool) *Lists {
	lists.modifiers.AddOrderBy(oDataOrderBy, ascending)
	return lists
}

/* Response helpers */

// Data response helper
func (listsResp *ListsResp) Data() []ListResp {
	collection, _ := normalizeODataCollection(*listsResp)
	lists := []ListResp{}
	for _, item := range collection {
		lists = append(lists, ListResp(item))
	}
	return lists
}

// Normalized returns normalized body
func (listsResp *ListsResp) Normalized() []byte {
	normalized, _ := NormalizeODataCollection(*listsResp)
	return normalized
}

/* Pagination helpers */

// ListsPage - paged items
type ListsPage struct {
	Items       ListsResp
	HasNextPage func() bool
	GetNextPage func() (*ListsPage, error)
}

// GetPaged gets Paged Items collection
func (lists *Lists) GetPaged() (*ListsPage, error) {
	data, err := lists.Get()
	if err != nil {
		return nil, err
	}
	res := &ListsPage{
		Items: data,
		HasNextPage: func() bool {
			return data.HasNextPage()
		},
		GetNextPage: func() (*ListsPage, error) {
			nextURL := data.NextPageURL()
			if nextURL == "" {
				return nil, fmt.Errorf("unable to get next page")
			}
			return NewLists(lists.client, nextURL, lists.config).GetPaged()
		},
	}
	return res, nil
}

// NextPageURL gets next page OData collection
func (listsResp *ListsResp) NextPageURL() string {
	return getODataCollectionNextPageURL(*listsResp)
}

// HasNextPage returns is true if next page exists
func (listsResp *ListsResp) HasNextPage() bool {
	return listsResp.NextPageURL() != ""
}
