// Code generated by `ggen -ent Profiles -conf -coll`; DO NOT EDIT.

package api

// Conf receives custom request config definition, e.g. custom headers, custom OData mod
func (profiles *Profiles) Conf(config *RequestConfig) *Profiles {
	profiles.config = config
	return profiles
}
