// Code generated by `ggen -ent RecycleBin -item RecycleBinItem -conf -coll -mods Select,Expand,Filter,Top,Skip,OrderBy -helpers Data,Normalized,Pagination`; DO NOT EDIT.

package api

import (
	"fmt"
)

// Conf receives custom request config definition, e.g. custom headers, custom OData mod
func (recycleBin *RecycleBin) Conf(config *RequestConfig) *RecycleBin {
	recycleBin.config = config
	return recycleBin
}

// Select adds $select OData modifier
func (recycleBin *RecycleBin) Select(oDataSelect string) *RecycleBin {
	recycleBin.modifiers.AddSelect(oDataSelect)
	return recycleBin
}

// Expand adds $expand OData modifier
func (recycleBin *RecycleBin) Expand(oDataExpand string) *RecycleBin {
	recycleBin.modifiers.AddExpand(oDataExpand)
	return recycleBin
}

// Filter adds $filter OData modifier
func (recycleBin *RecycleBin) Filter(oDataFilter string) *RecycleBin {
	recycleBin.modifiers.AddFilter(oDataFilter)
	return recycleBin
}

// Top adds $top OData modifier
func (recycleBin *RecycleBin) Top(oDataTop int) *RecycleBin {
	recycleBin.modifiers.AddTop(oDataTop)
	return recycleBin
}

// Skip adds $skiptoken OData modifier
func (recycleBin *RecycleBin) Skip(skipToken string) *RecycleBin {
	recycleBin.modifiers.AddSkip(skipToken)
	return recycleBin
}

// OrderBy adds $orderby OData modifier
func (recycleBin *RecycleBin) OrderBy(oDataOrderBy string, ascending bool) *RecycleBin {
	recycleBin.modifiers.AddOrderBy(oDataOrderBy, ascending)
	return recycleBin
}

/* Response helpers */

// Data response helper
func (recycleBinResp *RecycleBinResp) Data() []RecycleBinItemResp {
	collection, _ := normalizeODataCollection(*recycleBinResp)
	recycleBin := []RecycleBinItemResp{}
	for _, item := range collection {
		recycleBin = append(recycleBin, RecycleBinItemResp(item))
	}
	return recycleBin
}

// Normalized returns normalized body
func (recycleBinResp *RecycleBinResp) Normalized() []byte {
	normalized, _ := NormalizeODataCollection(*recycleBinResp)
	return normalized
}

/* Pagination helpers */

// RecycleBinPage - paged items
type RecycleBinPage struct {
	Items       RecycleBinResp
	HasNextPage func() bool
	GetNextPage func() (*RecycleBinPage, error)
}

// GetPaged gets Paged Items collection
func (recycleBin *RecycleBin) GetPaged() (*RecycleBinPage, error) {
	data, err := recycleBin.Get()
	if err != nil {
		return nil, err
	}
	res := &RecycleBinPage{
		Items: data,
		HasNextPage: func() bool {
			return data.HasNextPage()
		},
		GetNextPage: func() (*RecycleBinPage, error) {
			nextURL := data.NextPageURL()
			if nextURL == "" {
				return nil, fmt.Errorf("unable to get next page")
			}
			return NewRecycleBin(recycleBin.client, nextURL, recycleBin.config).GetPaged()
		},
	}
	return res, nil
}

// NextPageURL gets next page OData collection
func (recycleBinResp *RecycleBinResp) NextPageURL() string {
	return getODataCollectionNextPageURL(*recycleBinResp)
}

// HasNextPage returns is true if next page exists
func (recycleBinResp *RecycleBinResp) HasNextPage() bool {
	return recycleBinResp.NextPageURL() != ""
}
