// Code generated by `ggen -ent Subscriptions -item Subscription -conf -coll`; DO NOT EDIT.

package api

// Conf receives custom request config definition, e.g. custom headers, custom OData mod
func (subscriptions *Subscriptions) Conf(config *RequestConfig) *Subscriptions {
	subscriptions.config = config
	return subscriptions
}
