// Code generated by `ggen -ent Subscription -conf`; DO NOT EDIT.

package api

// Conf receives custom request config definition, e.g. custom headers, custom OData mod
func (subscription *Subscription) Conf(config *RequestConfig) *Subscription {
	subscription.config = config
	return subscription
}
