// Code generated by `ggen -ent Users -item User -conf -coll -mods Select,Expand,Filter,Top,Skip,OrderBy -helpers Data,Normalized,Pagination`; DO NOT EDIT.

package api

import (
	"fmt"
)

// Conf receives custom request config definition, e.g. custom headers, custom OData mod
func (users *Users) Conf(config *RequestConfig) *Users {
	users.config = config
	return users
}

// Select adds $select OData modifier
func (users *Users) Select(oDataSelect string) *Users {
	users.modifiers.AddSelect(oDataSelect)
	return users
}

// Expand adds $expand OData modifier
func (users *Users) Expand(oDataExpand string) *Users {
	users.modifiers.AddExpand(oDataExpand)
	return users
}

// Filter adds $filter OData modifier
func (users *Users) Filter(oDataFilter string) *Users {
	users.modifiers.AddFilter(oDataFilter)
	return users
}

// Top adds $top OData modifier
func (users *Users) Top(oDataTop int) *Users {
	users.modifiers.AddTop(oDataTop)
	return users
}

// Skip adds $skiptoken OData modifier
func (users *Users) Skip(skipToken string) *Users {
	users.modifiers.AddSkip(skipToken)
	return users
}

// OrderBy adds $orderby OData modifier
func (users *Users) OrderBy(oDataOrderBy string, ascending bool) *Users {
	users.modifiers.AddOrderBy(oDataOrderBy, ascending)
	return users
}

/* Response helpers */

// Data response helper
func (usersResp *UsersResp) Data() []UserResp {
	collection, _ := normalizeODataCollection(*usersResp)
	users := []UserResp{}
	for _, item := range collection {
		users = append(users, UserResp(item))
	}
	return users
}

// Normalized returns normalized body
func (usersResp *UsersResp) Normalized() []byte {
	normalized, _ := NormalizeODataCollection(*usersResp)
	return normalized
}

/* Pagination helpers */

// UsersPage - paged items
type UsersPage struct {
	Items       UsersResp
	HasNextPage func() bool
	GetNextPage func() (*UsersPage, error)
}

// GetPaged gets Paged Items collection
func (users *Users) GetPaged() (*UsersPage, error) {
	data, err := users.Get()
	if err != nil {
		return nil, err
	}
	res := &UsersPage{
		Items: data,
		HasNextPage: func() bool {
			return data.HasNextPage()
		},
		GetNextPage: func() (*UsersPage, error) {
			nextURL := data.NextPageURL()
			if nextURL == "" {
				return nil, fmt.Errorf("unable to get next page")
			}
			return NewUsers(users.client, nextURL, users.config).GetPaged()
		},
	}
	return res, nil
}

// NextPageURL gets next page OData collection
func (usersResp *UsersResp) NextPageURL() string {
	return getODataCollectionNextPageURL(*usersResp)
}

// HasNextPage returns is true if next page exists
func (usersResp *UsersResp) HasNextPage() bool {
	return usersResp.NextPageURL() != ""
}
