// Code generated by `ggen -ent Views -item View -conf -coll -mods Select,Expand,Filter,Top,Skip,OrderBy -helpers Data,Normalized,Pagination`; DO NOT EDIT.

package api

import (
	"fmt"
)

// Conf receives custom request config definition, e.g. custom headers, custom OData mod
func (views *Views) Conf(config *RequestConfig) *Views {
	views.config = config
	return views
}

// Select adds $select OData modifier
func (views *Views) Select(oDataSelect string) *Views {
	views.modifiers.AddSelect(oDataSelect)
	return views
}

// Expand adds $expand OData modifier
func (views *Views) Expand(oDataExpand string) *Views {
	views.modifiers.AddExpand(oDataExpand)
	return views
}

// Filter adds $filter OData modifier
func (views *Views) Filter(oDataFilter string) *Views {
	views.modifiers.AddFilter(oDataFilter)
	return views
}

// Top adds $top OData modifier
func (views *Views) Top(oDataTop int) *Views {
	views.modifiers.AddTop(oDataTop)
	return views
}

// Skip adds $skiptoken OData modifier
func (views *Views) Skip(skipToken string) *Views {
	views.modifiers.AddSkip(skipToken)
	return views
}

// OrderBy adds $orderby OData modifier
func (views *Views) OrderBy(oDataOrderBy string, ascending bool) *Views {
	views.modifiers.AddOrderBy(oDataOrderBy, ascending)
	return views
}

/* Response helpers */

// Data response helper
func (viewsResp *ViewsResp) Data() []ViewResp {
	collection, _ := normalizeODataCollection(*viewsResp)
	views := []ViewResp{}
	for _, item := range collection {
		views = append(views, ViewResp(item))
	}
	return views
}

// Normalized returns normalized body
func (viewsResp *ViewsResp) Normalized() []byte {
	normalized, _ := NormalizeODataCollection(*viewsResp)
	return normalized
}

/* Pagination helpers */

// ViewsPage - paged items
type ViewsPage struct {
	Items       ViewsResp
	HasNextPage func() bool
	GetNextPage func() (*ViewsPage, error)
}

// GetPaged gets Paged Items collection
func (views *Views) GetPaged() (*ViewsPage, error) {
	data, err := views.Get()
	if err != nil {
		return nil, err
	}
	res := &ViewsPage{
		Items: data,
		HasNextPage: func() bool {
			return data.HasNextPage()
		},
		GetNextPage: func() (*ViewsPage, error) {
			nextURL := data.NextPageURL()
			if nextURL == "" {
				return nil, fmt.Errorf("unable to get next page")
			}
			return NewViews(views.client, nextURL, views.config).GetPaged()
		},
	}
	return res, nil
}

// NextPageURL gets next page OData collection
func (viewsResp *ViewsResp) NextPageURL() string {
	return getODataCollectionNextPageURL(*viewsResp)
}

// HasNextPage returns is true if next page exists
func (viewsResp *ViewsResp) HasNextPage() bool {
	return viewsResp.NextPageURL() != ""
}
