// Code generated by `ggen -ent Webs -item Web -conf -coll -mods Select,Expand,Filter,Top,Skip,OrderBy -helpers Data,Normalized,Pagination`; DO NOT EDIT.

package api

import (
	"fmt"
)

// Conf receives custom request config definition, e.g. custom headers, custom OData mod
func (webs *Webs) Conf(config *RequestConfig) *Webs {
	webs.config = config
	return webs
}

// Select adds $select OData modifier
func (webs *Webs) Select(oDataSelect string) *Webs {
	webs.modifiers.AddSelect(oDataSelect)
	return webs
}

// Expand adds $expand OData modifier
func (webs *Webs) Expand(oDataExpand string) *Webs {
	webs.modifiers.AddExpand(oDataExpand)
	return webs
}

// Filter adds $filter OData modifier
func (webs *Webs) Filter(oDataFilter string) *Webs {
	webs.modifiers.AddFilter(oDataFilter)
	return webs
}

// Top adds $top OData modifier
func (webs *Webs) Top(oDataTop int) *Webs {
	webs.modifiers.AddTop(oDataTop)
	return webs
}

// Skip adds $skiptoken OData modifier
func (webs *Webs) Skip(skipToken string) *Webs {
	webs.modifiers.AddSkip(skipToken)
	return webs
}

// OrderBy adds $orderby OData modifier
func (webs *Webs) OrderBy(oDataOrderBy string, ascending bool) *Webs {
	webs.modifiers.AddOrderBy(oDataOrderBy, ascending)
	return webs
}

/* Response helpers */

// Data response helper
func (websResp *WebsResp) Data() []WebResp {
	collection, _ := normalizeODataCollection(*websResp)
	webs := []WebResp{}
	for _, item := range collection {
		webs = append(webs, WebResp(item))
	}
	return webs
}

// Normalized returns normalized body
func (websResp *WebsResp) Normalized() []byte {
	normalized, _ := NormalizeODataCollection(*websResp)
	return normalized
}

/* Pagination helpers */

// WebsPage - paged items
type WebsPage struct {
	Items       WebsResp
	HasNextPage func() bool
	GetNextPage func() (*WebsPage, error)
}

// GetPaged gets Paged Items collection
func (webs *Webs) GetPaged() (*WebsPage, error) {
	data, err := webs.Get()
	if err != nil {
		return nil, err
	}
	res := &WebsPage{
		Items: data,
		HasNextPage: func() bool {
			return data.HasNextPage()
		},
		GetNextPage: func() (*WebsPage, error) {
			nextURL := data.NextPageURL()
			if nextURL == "" {
				return nil, fmt.Errorf("unable to get next page")
			}
			return NewWebs(webs.client, nextURL, webs.config).GetPaged()
		},
	}
	return res, nil
}

// NextPageURL gets next page OData collection
func (websResp *WebsResp) NextPageURL() string {
	return getODataCollectionNextPageURL(*websResp)
}

// HasNextPage returns is true if next page exists
func (websResp *WebsResp) HasNextPage() bool {
	return websResp.NextPageURL() != ""
}
